version: '2.1'
services:
    postgres:
        image: fetchq/fetchq:9.6-1.2.0
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres_db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER-fetchq}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-fetchq}
            POSTGRES_DB: ${POSTGRES_DB-fetchq}
    
    queue:
        image: node:9.9
        depends_on:
            - postgres
        volumes:
            - ./app:/usr/src/app
            - ./data/node_modules:/usr/src/app/node_modules
        environment:
            LOG_LEVEL: ${LOG_LEVEL-verbose}
            PGUSER: ${POSTGRES_USER-fetchq}
            PGPASSWORD: ${POSTGRES_PASSWORD-fetchq}
            PGDATABASE: ${POSTGRES_DB-fetchq}
            PGHOST: ${POSTGRES_HOST-postgres}
            PGPORT: ${POSTGRES_PORT-5432}
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:prod" ]
        restart: always
    