version: '2.1'
services:
    postgres:
        image: fetchq/fetchq:9.6-1.1.0
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER-fetchq}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-fetchq}
            POSTGRES_DB: ${POSTGRES_DB-fetchq}
    
    queue:
        image: node:9.9
        depends_on:
            - postgres
        volumes:
            - ./app:/usr/src/app
        environment:
            POSTGRES_USER: ${POSTGRES_USER-fetchq}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-fetchq}
            POSTGRES_DB: ${POSTGRES_DB-fetchq}
            POSTGRES_HOST: ${POSTGRES_HOST-postgres}
            POSTGRES_PORT: ${POSTGRES_PORT-5432}
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start:prod" ]
        restart: always
    